import { NextResponse } from "next/server";

const ACCOUNTS = [
  {
    id: "raisin",
    bank: "Raisin",
    apy: 4.0,
    minDeposit: "$1",
    monthlyFee: "$0",
    fdic: true,
    notes:
      "APY via partner banks on the Raisin marketplace; rate may vary by bank and term.",
  },
  {
    id: "lendingclub",
    bank: "LendingClub",
    apy: 4.0,
    minDeposit: "$100",
    monthlyFee: "$0",
    fdic: true,
    notes: "High-yield savings; confirm current APY tiers and requirements on site.",
  },
  {
    id: "sofi",
    bank: "SoFi",
    apy: 4.0,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes:
      "Often requires direct deposit or other qualifiers for top tier; verify eligibility.",
  },
  {
    id: "everbank",
    bank: "EverBank",
    apy: 3.9,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "Rates promotional; check intro vs ongoing APY and balance tiers.",
  },
  {
    id: "cit",
    bank: "CIT Bank",
    apy: 3.75,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "Platinum Savings may require minimum balance for stated APY.",
  },
  {
    id: "customers",
    bank: "Customers Bank",
    apy: 3.75,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "High-yield product; confirm if rate is promotional or ongoing.",
  },
  {
    id: "briodirect",
    bank: "BrioDirect",
    apy: 3.75,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "Online-only; funding and transfer limits may apply.",
  },
  {
    id: "synchrony",
    bank: "Synchrony",
    apy: 3.7,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "High Yield Savings; APY can change with Fed moves.",
  },
  {
    id: "cibc",
    bank: "CIBC",
    apy: 3.66,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "Agility Online Savings; verify residency and product availability.",
  },
  {
    id: "marcus",
    bank: "Marcus by Goldman Sachs",
    apy: 3.65,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "No-penalty CDs also offered; savings APY is variable.",
  },
  {
    id: "tab",
    bank: "TAB Bank",
    apy: 3.61,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "High Yield Savings; confirm tier requirements for listed rate.",
  },
  {
    id: "salem-five",
    bank: "Salem Five",
    apy: 3.61,
    minDeposit: "$10",
    monthlyFee: "$0",
    fdic: true,
    notes: "Direct Bank eOne Savings; geographic or new-customer rules may apply.",
  },
  {
    id: "barclays",
    bank: "Barclays",
    apy: 3.6,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "Online savings; transfers may take standard ACH timing.",
  },
  {
    id: "discover",
    bank: "Discover",
    apy: 3.4,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "Online savings; competitive but verify current promotional offers.",
  },
  {
    id: "capital-one",
    bank: "Capital One",
    apy: 3.3,
    minDeposit: "$0",
    monthlyFee: "$0",
    fdic: true,
    notes: "360 Performance Savings; widely available; rate is variable.",
  },
];

export async function GET() {
  const sorted = [...ACCOUNTS].sort((a, b) => b.apy - a.apy);
  return NextResponse.json(sorted);
}
